[project]
name = "models-open223-info"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Gabe Fierro", email = "gtfierro@mines.edu" }
]
dependencies = [
    "jupyter-book>=0.15.1",
    "toml>=0.10.2",
    "sphinxcontrib-mermaid>=0.9.2",
    "rdflib>=7.0.0",
    "pyontoenv==0.1.9a3",
    "brickschema==0.7.4a9",
    "nbformat>=5.10.4",
    "jupyterlab>=4.2.4",
    "buildingmotif[topquadrant] @ git+https://github.com/NREL/buildingmotif.git@develop"
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
