[project]
name = "models-open223-info"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "brick-tq-shacl==0.3.4a1",
    "jupyter-book>=1.0.2",
    "jupyterlab>=4.2.5",
    "nbformat>=5.10.4",
    "pyontoenv>=0.1.9",
    "rdflib>=7.0.0",
    "sphinxcontrib-mermaid>=0.9.2",
    "toml>=0.10.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
