# https://github.com/executablebooks/github-action-demo/blob/master/.github/workflows/book.yml
name: deploy-book

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get ontoenv
      run: |
        wget https://github.com/gtfierro/ontoenv-rs/releases/download/v0.2.0a4/ontoenv_v0.2.0a4_x86_64_linux_gnu
        chmod +x ontoenv_v0.2.0a4_x86_64_linux_gnu
        sudo mv ontoenv_v0.2.0a4_x86_64_linux_gnu /usr/local/bin/ontoenv

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: build examples
      run: |
        bash build_examples.sh

    - name: build jupyter book
      run: |
        uv run jupyter-book build .
        ls -l _build/html

    - name: fix CNAME
      run: |
        cp CNAME _build/html/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
